### ISSUE TITLE
Clang: Flexible array member with non-trivial destruction

### ISSUE THREAD

**Issue by mratsim** [status-im/nimbus#2]
Currently tests are failing for me on MacOS with Clang:

```
Error: execution of an external compiler program 'clang++ -c  -w -I/Users/<User>/.nimble/pkgs/ttmath-0.5.0  -I'/Users/<User>/.choosenim/toolchains/nim-#devel/lib' -o /Users/<User>/Programming/Status/nimbus/tests/nimcache/nimbus_stack_test.o /Users/<User>/Programming/Status/nimbus/tests/nimcache/nimbus_stack_test.cpp' failed with exit code: 1

/Users/<User>/Programming/Status/nimbus/tests/nimcache/nimbus_stack_test.cpp:242:29: error: flexible array member 'data' of type 'TY_fSgjjjotfhO8wSAxXj6bfw []' with non-trivial destruction
  TY_fSgjjjotfhO8wSAxXj6bfw data[SEQ_DECL_SIZE];
```

The offending line is:

```C++
struct tySequence_sp47cI5UpQ9bwXDfsT164pg : TGenericSeq {
  TY_fSgjjjotfhO8wSAxXj6bfw data[SEQ_DECL_SIZE];
};
```

It is used at several places in the generated C++ code, full output available [here](https://gist.github.com/mratsim/d3ebfef95a134f66f91d3d6535d32189).

Edit: GCC-7 does not have the same issue

**Comment by arnetheduck** [comment]
The issue here is `SEQ_DECL_SIZE` which is declared empty (in `nimbase.h`) - this leads to an empty ("flexible") array - that's not part of the `C++` standard (it's a `C` only feature) so llvm is right to reject it, even if it happens to work for gcc (I wouldn't be surprised if gcc rejected it in pedantic mode or with extensions turned off)

**Comment by mratsim** [comment]
Closed by https://github.com/status-im/nimbus/commit/1d81a7c7ba2ce6f6ea24ffa0341f67e8bd9d72bb and #5
