### ISSUE TITLE
Add build and test instructions

### ISSUE THREAD

**Issue by drasko** [status-im/nimbus#43]
Please add basic build/test/install and deploy/usage instructions to README, so people can try out and understand better the implementation.

**Comment by mratsim** [comment]
Hello @drasko, thank you for following us on this.

Right now, Nimbus is mostly on automated port from Py-EVM.

We are building the individual components and refactoring the port to be more in line with Nim (and not Python) but there is unfortunately no CLI interface at the moment.

I will update the Readme so that you can at least run the test suite and decompile smart contract.

**Comment by drasko** [comment]
@mratsim - thanks a lot. I would like to give it a try.

I think it will be helpful wo wider community, as Nim is emerging language, and not everybody is familiar with it.

A simple compilation and run procedures (just the basic commands and explanations, nothing fancy) would be sufficient and would lower the barrier of entry in experimenting with `nimbus`.

I am very interested in this project and following it closely, and will try to help in the future.
